package com.summercamp.project.agent;

public enum AgentPlanErrorCode {
    JSON_PARSE_FAILED,
    UNKNOWN_FIELD,
    UNKNOWN_ACTION,
    GOAL_MISMATCH,
    INVALID_INPUTS,
    STEP_COUNT_INVALID,
    BUSINESS_TASK_COUNT_INVALID,
    DUPLICATE_STEP_ID,
    UNKNOWN_DEPENDENCY,
    SELF_DEPENDENCY,
    DEPENDENCY_CYCLE,
    VALIDATE_MISSING,
    VALIDATE_DUPLICATE,
    SYNTHESIZE_MISSING,
    SYNTHESIZE_DUPLICATE,
    SYNTHESIZE_NOT_LAST,
    SYNTHESIZE_VALIDATION_DEPENDENCY_INVALID,
    MISSING_REQUIRED_EXERCISE_ACTION,
    MISSING_REQUIRED_MEAL_ACTION,
    MISSING_REQUIRED_WEATHER_ACTION,
    OTHER_PLAN_VALIDATION_ERROR
}
